DATA SEGMENT
    DATA_START DB 51H, 3AH,95H, 8DH, 90H,
    DB 0A7H, 0C1H, 77H, 24H, 0B1H 
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX
    MOV DI,10
LOOP1: 
    MOV SI,OFFSET DATA_START
    DEC DI
    MOV CX,DI 
    JZ END1
LOOP2:
    MOV AL,[SI]
    INC SI 
    MOV BL,[SI]
    CMP AL,BL
    JA EXCHANGE
    JMP CONTINUE
EXCHANGE:
    MOV [SI],AL
    MOV [SI-1],BL
CONTINUE:
    LOOP LOOP2   

    JMP LOOP1
END1:  
    MOV CX,10 
    MOV DI,3000H
LOOP3: 
    MOV AX,[SI]
    MOV [DI],AX
    INC SI
    INC DI
    LOOP LOOP3
    
    MOV AX,4C00H
    INT 21H
CODE ENDS
END START