DATA SEGMENT
    START_DATA DB 05CH,0A1H,86H
DATA ENDS
CODE SEGMENT
    ASSUME CS:CODE DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV SI,OFFSET START_DATA
      MOV AL,[SI]
      CMP AL,[SI+1]
      JA LOOP1
      MOV AL,[SI+1]
LOOP1:CMP AL,[SI+2]
      JA LOOP2 
      MOV AL,[SI+2]
LOOP2:MOV BX,3000H
      MOV [BX],AL 
      
      MOV AX,4C00H
      INT 21H
      CODE ENDS
END START