DATA SEGMENT
    START_DATA DB 8BH
DATA ENDS
CODE SEGMENT
ASSUME CS:CODE DS:DATA
START:MOV AX,DATA
      MOV DS,AX
      MOV AL,START_DATA
      TEST AL,01H
      JZ LOOP1
      TEST AL,80H
      JNZ LOOP2
LOOP1:MOV BX,100H
      MOV [BX],0
      MOV AH,4CH
      INT 21H
LOOP2:MOV BX,100H
      MOV [BX],1
      MOV AH,4CH
      INT 21H
CODE ENDS
END START